//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PizzeriaV2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BestallningMatratt
    {
        public int MatrattID { get; set; }
        public int BestallningID { get; set; }
        public int Antal { get; set; }
    
        public virtual Bestallning Bestallning { get; set; }
        public virtual Matratt Matratt { get; set; }
    }
}
