//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace PizzeriaV2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kund
    {
        public Kund()
        {
            this.Bestallnings = new HashSet<Bestallning>();
        }
    
        public int KundID { get; set; }

        [Required(ErrorMessage = "Namn är obligatoriskt")]
        [StringLength(100, ErrorMessage = "Namn får vara max 100 tecken")]
        public string Namn { get; set; }

        [Required(ErrorMessage = "Gatuadress är obligatoriskt")]
        [StringLength(50, ErrorMessage = "Gatuadress får vara max 50 tecken")]
        public string Gatuadress { get; set; }

        [Required(ErrorMessage = "Post nummer är obligatoriskt")]
        [StringLength(20, ErrorMessage = "Postnummer får vara max 20 tecken")]
        public string Postnr { get; set; }

        [Required(ErrorMessage = "Postort är obligatoriskt")]
        [StringLength(100, ErrorMessage = "Postort får vara max 100 tecken")]
        public string Postort { get; set; }

        [EmailAddress(ErrorMessage = "Felaktig emailadress")]
        public string Email { get; set; }

        [RegularExpression(@"^[0-9]{0,15}$", ErrorMessage = "Felaktigt telefonnummer")]
        public string Telefon { get; set; }

        [Required(ErrorMessage = "Användarnamn är obligatoriskt")]
        [StringLength(20, ErrorMessage = "Användarnamn får vara max 20 tecken")]
        public string AnvandarNamn { get; set; }

        [Required(ErrorMessage = "Lösenord är obligatoriskt")]
        [StringLength(20, ErrorMessage = "Lösenord får vara max 20 tecken")]
        public string Losenord { get; set; }
    
        public virtual ICollection<Bestallning> Bestallnings { get; set; }
    }
}
