//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PizzeriaV2.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PizzaConnection : DbContext
    {
        public PizzaConnection()
            : base("name=PizzaConnection")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Bestallning> Bestallnings { get; set; }
        public virtual DbSet<BestallningMatratt> BestallningMatratts { get; set; }
        public virtual DbSet<Kund> Kunds { get; set; }
        public virtual DbSet<Matratt> Matratts { get; set; }
        public virtual DbSet<MatrattTyp> MatrattTyps { get; set; }
        public virtual DbSet<Produkt> Produkts { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
    }
}
