//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PizzeriaV2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Produkt
    {
        public Produkt()
        {
            this.Matratts = new HashSet<Matratt>();
        }
    
        public int ProduktID { get; set; }
        public string ProduktNamn { get; set; }
    
        public virtual ICollection<Matratt> Matratts { get; set; }
    }
}
